### ISSUE TITLE
Menu not showing mobile

### ISSUE THREAD

**Issue by TinyLightBold** [nuxt/nuxt.com#1376]
First of all. A great job on the new design :). 

Only got 1 problem occuring:

When you open the site on mobile, the menu stays in desktop style.
Occurs on A13. 1, Chrome, Kiwi and Edge.

It's for me too late atm to check what going wrong.
But wanted to let you know.

**Comment by TinyLightBold** [comment]
![Screenshot_2023-10-18-22-02-55-86_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/nuxt/nuxt.com/assets/11291884/99da38f9-f82d-450c-bafe-814b0e40079c)

**Comment by benjamincanac** [comment]
Thanks for noticing, there was a hick-up in the `@nuxt/ui-pro` edge package! This should now be fixed 😊
