### ISSUE TITLE
Jobs page not load on hard refresh

### ISSUE THREAD

**Issue by Gruce** [nuxt/nuxt.com#1377]
Hello,

Jobs page is not loading on hard refresh due to `properties of null (reading 'head')`:

![image](https://github.com/nuxt/nuxt.com/assets/5357529/6e1e5473-6b3c-4efe-8aac-fee70f32eae9)

Thank you.

**Comment by benjamincanac** [comment]
I haven't been able to reproduce this, is the issue is still happening for you?

**Comment by Gruce** [comment]
> I haven't been able to reproduce this, is the issue still happening for you?

It's working fine now.
