### ISSUE TITLE
Latest Blog entry is not linking to the latest!

### ISSUE THREAD

**Issue by davidschubert** [nuxt/nuxt.com#1386]
![IMG_2082](https://github.com/nuxt/nuxt.com/assets/32385904/72ffb9e0-b830-4392-a687-dfae32babd18)

button on top is linking to the „new website“ blog entry and not the latest one.

**Comment by madebyfabian** [comment]
Fixed by https://github.com/nuxt/nuxt.com/commit/b4e71f88c2ee12f960bb1aaf4b6a4995e90113eb
