### ISSUE TITLE
Copy code button is not the same on every nuxt website

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt.com#1390]
Hello,

Copy button from a code block is not the same on every nuxt website. I don't know if this should be fixed in nuxt/ui or in each website.

nuxt.com

![image](https://github.com/nuxt/nuxt.com/assets/45267552/25ea3358-3668-432c-8db7-a88002fb8e2a)

content.nuxt.com

![image](https://github.com/nuxt/nuxt.com/assets/45267552/22bae1c8-6353-4546-ae54-291b85c1ca34)

image.nuxt.com

![image](https://github.com/nuxt/nuxt.com/assets/45267552/ebe40f79-9d4d-458c-9f77-985e5790351d)

It seems that docs for solutions are unified but there is some minor differences with nuxt.com like the background.

**Comment by benjamincanac** [comment]
This is intentional, the module docs uses the default `@nuxt/ui-pro` which uses heroicons but on nuxt.com we've customized it to use `Phosphor` and changed the background.
