### ISSUE TITLE
nuxt config returning 404

### ISSUE THREAD

**Issue by DerSimeon** [nuxt/nuxt.com#1391]
Going on this Page: https://nuxt.com/docs/getting-started/configuration and clicking on "nuxt.config.ts" results in a 404
also going to https://nuxt.com/docs/guide and going to nuxt.config.ts via the directory structure also returns into 404.

**Comment by Hebilicious** [comment]
It's returning a 404 for me as well. Could this be due to the fact that there's a `.` in the url ?

**Comment by Atinux** [comment]
The link should be https://nuxt.com/docs/api/nuxt-config

**Comment by mrleblanc101** [comment]
Yeah the Algolia Search also direct to a 404, maybe a reindexation is needed ?
![2023-10-23 13 21 46](https://github.com/nuxt/nuxt.com/assets/17392251/f7322422-69f2-4582-913f-e1c951af5500)

**Comment by Atinux** [comment]
Should be fixed now
