### ISSUE TITLE
Missing links `to` for modules contributors

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt.com#1392]
Hello,

On a module page, there is the list of contributors. When the mouse hover one of them, it's like you can click on it but there is no link.

In this function, https://github.com/nuxt/nuxt.com/blob/aa7bc1ba97d737b4f049c415b3fa527549b01485/pages/modules/%5Bslug%5D.vue#L40, there is no `to` key for the link.

**Comment by benjamincanac** [comment]
Thanks for the report 😊
