### ISSUE TITLE
Icons Shrinking below 900px width and in Tablet View(768) on enterprise support page

### ISSUE THREAD

**Issue by MuhammadHafijur** [nuxt/nuxt.com#1399]
On the "Enterprise Support" page, the icons are shrinking when the device width is less than 900 pixels or in tablet view(768px). To resolve this, we can apply the Tailwind CSS class `shrink-0` to three specific child elements and it will prevent shrinking. It will work fine from mobile to desktop device. I'm new to open source contribution. Any suggestions or advice are appreciated.

**Current code**
```
<div class="flex flex-col sm:flex-row items-center gap-4 mb-8">
    <div class="w-14 h-14 bg-gray-100 dark:bg-gray-800 ring-1 ring-gray-300 dark:ring-gray-700 rounded-md flex items-center justify-center">
      <UIcon :name="icon" class="w-8 h-8" />
    </div>

    <div>
      <h2 class="text-lg font-semibold my-0">
        <ContentSlot :use="$slots.title" unwrap="p" />
      </h2>

      <p class="text-gray-500 dark:text-gray-400 text-base mt-1 mb-0">
        <ContentSlot :use="$slots.description" unwrap="p" />
      </p>
    </div>
  </div>
```
**My Solution**
```
<div class="flex flex-col sm:flex-row items-center gap-4 mb-8">
    <div class="w-14 h-14 bg-gray-100 dark:bg-gray-800 ring-1 shrink-0 ring-gray-300 dark:ring-gray-700 rounded-md flex items-center justify-center">
      <UIcon :name="icon" class="w-8 h-8" />
    </div>

    <div>
      <h2 class="text-lg font-semibold my-0">
        <ContentSlot :use="$slots.title" unwrap="p" />
      </h2>

      <p class="text-gray-500 dark:text-gray-400 text-base mt-1 mb-0">
        <ContentSlot :use="$slots.description" unwrap="p" />
      </p>
    </div>
  </div>
```
**Example 1:**
[
![nuxt com_](https://github.com/nuxt/nuxt.com/assets/85216180/9d42237d-d027-48b3-8bc0-35d183d55059)
](url)

**Example 2**
![nuxt com_ (1)](https://github.com/nuxt/nuxt.com/assets/85216180/1d284fc6-da78-41a4-8e42-c62772d1f075)

**After Solution**
![localhost_3000_enterprise_support](https://github.com/nuxt/nuxt.com/assets/85216180/c414a61f-0745-4b04-b5af-73168152aad3)

Should I create a pull req?

```[tasklist]
### Tasks
```

**Comment by benjamincanac** [comment]
Sure thing! Thanks for catching this 😊

**Comment by MuhammadHafijur** [comment]
Thanks for the reply @benjamincanac . I've made a pull req (https://github.com/nuxt/nuxt.com/pull/1401) . Looking forward to it.
