### ISSUE TITLE
docs: TOC sticky position is not working on mobile

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/nuxt.com#1412]
The sticky position of Table of Contents isn't functioning on mobil. I think it's because of the `div` from `$slots.right` of `UPage`.

<img width="958" alt="Screenshot 2023-11-07 at 12 08 42 AM" src="https://github.com/nuxt/nuxt.com/assets/38922203/704ca39b-c8e2-4915-840f-21dfcf493c1d">

**Comment by Atinux** [comment]
We talked about it with @benjamincanac but we could not find a solution to make it work, I think it's not that bad

**Comment by arashsheyda** [comment]
@Atinux I have a potential solution in mind, should I open a PR?

**Comment by Atinux** [comment]
Sure!
