### ISSUE TITLE
Nuxt Config Page misses all the comment from the code

### ISSUE THREAD

**Issue by MiniDigger** [nuxt/nuxt.com#1415]
I haven't looked at how it is supposed to work, but I am pretty sure that this page included descriptions of all options before:
https://nuxt.com/docs/api/nuxt-config
the descriptions are still in the code (see https://github.com/nuxt/nuxt/blob/main/packages/schema/src/config/app.ts for example), just not rendered on the website anymore. 
I am not sure when this broke, maybe with the new website? 

edit: found out how its generated (https://github.com/nuxt/nuxt.com/blob/9084f3b31b9c8c3428b67e50def1a79c89d14de1/server/plugins/docs-config.ts#L17) looks like the schema doesnt include comments (anymore?) https://unpkg.com/@nuxt/schema@3.8.1/schema/config.schema.json so maybe this is an issue on the nuxt repo with the schema generation instead?

**Comment by pi0** [comment]
(self assigned to investigate)

**Comment by Atinux** [comment]
Would you have time to look at it? @pi0

**Comment by MiniDigger** [comment]
decided to do some digging, turns out, commenting out this line (in node modules) fixes this issue for nuxt
https://github.com/unjs/untyped/blob/main/src/loader/babel.ts#L65
for some reason that transformer is called twice per object now and the second call overrides the schema of the first one, while not being able to read the jsdoc, as such the title and description vanish.

idk why that would change, I had some success in downgrading jiti to 1.20.0 but cant replicate that anymore.

**Comment by mukundshah** [comment]
Is not there any temporary patch or workaround for this?

**Comment by danielroe** [comment]
Confirmed that this is resolved with jiti@1.20.0 pinned in the Nuxt workspace.

**Comment by MiniDigger** [comment]
https://github.com/unjs/untyped/commit/7a941412c2ca6c78f1fc1bc6a7fb9f2701d4be2a

**Comment by danielroe** [comment]
Now resolved! Thank you for your investigation ❤️
