### ISSUE TITLE
Menus close before you can use them

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt.com#1420]
On my mac (Chrome 119/Firefox 119) the top dropdown menus are too far away from their triggers so they close before you can use them.  It seems fine in Safari 17.0 / Edge 119?!

https://github.com/nuxt/nuxt.com/assets/2112282/f575fd79-c08c-4e8f-8461-197c472cff41

**Comment by benjamincanac** [comment]
Duplicate of #1419

**Comment by benjamincanac** [comment]
Should have been fixed already!

**Comment by hecktarzuli** [comment]
Looks good now.
