### ISSUE TITLE
Translations for docs

### ISSUE THREAD

**Issue by CyanChanges** [nuxt/nuxt.com#1448]
Why Nuxt v2 docs get translations, but Nuxt v3 docs don't?

**Comment by Coiggahou2002** [comment]
This framework is really awesome. It would be even better if there is a Chinese version documentation! If maintainers @Atinux @danielroe  thinks  this is feasible, I am willing to do my best to help with the translation.

**Comment by Atinux** [comment]
I think there is an ongoing work done on https://nuxt.com.cn

I know that @antfu know the authors if it may help

**Comment by CyanChanges** [comment]
> I think there is an ongoing work done on https://nuxt.com.cn
> 
> I know that @antfu know the authors if it may help
> 
> We could probably add a dropdown for the language switch though 🤔

Thanks, i hope to see that soon

I found that @codingcn 
may make the nuxt.com.cn
The original discussion here:
https://github.com/nuxt/nuxt/discussions/16208#discussion-4773519

**Comment by volkanakkus** [comment]
> I think there is an ongoing work done on https://nuxt.com.cn
> 
> I know that [@antfu](https://github.com/antfu) know the authors if it may help
> 
> We could probably add a dropdown for the language switch though 🤔

If you are planning to add the switch button, I’m ready for Turkish translations.
