### ISSUE TITLE
About vue@3.4.3 causing hydration mismatch

### ISSUE THREAD

**Issue by pacmandoh** [nuxt/nuxt.com#1467]
After using `pnpm update` to upgrade vue to 3.4.3, the console throws a lot of `Hydration mismatch`. If I am using vue 3.3.13, no `Hydration mismatch` warnings will be thrown.

<img width="1402" alt="SCR-20240103-qagg" src="https://github.com/nuxt/nuxt.com/assets/133459587/188ac1c4-e19a-4570-a5d0-4863c92a7bda">

**Comment by Atinux** [comment]
Hey @pacmandoh 

Some hydration mismatch are being solved in Nuxt UI (regression from Vue 3.4 missing a `useId()` system), we are working on nuxt to fix this (https://github.com/nuxt/nuxt/pull/23368)

Also, make sure to open an incognito window to avoid extension to update the HTML, it can also lead to hydration mismatch.

**Comment by pacmandoh** [comment]
> Hey @pacmandoh 
> 
> 
> 
> Some hydration mismatch are being solved in Nuxt UI (regression from Vue 3.4 missing a `useId()` system), we are working on nuxt to fix this (https://github.com/nuxt/nuxt/pull/23368)
> 
> 
> 
> Also, make sure to open an incognito window to avoid extension to update the HTML, it can also lead to hydration mismatch.

thanks! ❤️

**Comment by pacmandoh** [comment]
@manniL No problem at all! 😆
