### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.com#1475]
See https://nuxt.com/docs/getting-started/transitions

Do we need to set CORS headers in cloudinary account?

**Comment by manniL** [comment]
Related? https://github.com/nuxt/nuxt/issues/25137

**Comment by busybox11** [comment]
That would make sense.

<img width="693" alt="DevTools screenshot of Nuxt's docs website, showing requests blocked by COEP" src="https://github.com/nuxt/nuxt.com/assets/29630035/52fe3a52-7475-4a1c-a1e2-f45176675f79">

The requests are blocked by `coep`, which has been set to `require-corp`.

**Comment by antfu** [comment]
Let's revert the CORS for now, I'll try to find another solution
