### ISSUE TITLE
Page subheadings do not have code formatting applied

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt.com#1485]
It would be a nice-to-have feature to have any code snippets formatted in the subheadings. An example here:
https://nuxt.com/docs/api/advanced/import-meta

![image](https://github.com/nuxt/nuxt.com/assets/48835293/ae84c25c-d3ed-43d3-93c8-5fb80a61e588)

**Comment by Atinux** [comment]
I think we should avoid adding code-formatting for the description as much as possible since this description is also set in the `<meta>` description @DamianGlowala

**Comment by DamianGlowala** [comment]
Wouldn't it only modify the visual layer and leave the meta description untouched? (I might be unaware of how these two can possibly be related.)

**Comment by Atinux** [comment]
It is possible but so far we will have an hydration error by using the MDC component will create a `<p>` inside another `<p>`.

I think this is fine for now for this formatting.

**Comment by DamianGlowala** [comment]
Alright, let's leave it as is! :) thanks for explaining
