### ISSUE TITLE
Dead showcase links

### ISSUE THREAD

**Issue by isakgustavsen** [nuxt/nuxt.com#1530]
Multiple links in showcase links to either dead sites or dead pages on the sites. I have attached a few. Also the russian mcdonalds site is on there
https://mcdonalds.ru/
https://ai.marketing/user/robot
https://game.fonts.adobe.com/
https://annual.awwwards.com/
https://globalmaintainersummit.github.com/
https://vintageria.it/
https://hyundaiusa.com/

**Comment by Atinux** [comment]
Removed, should be ready on next deploy. Thank you!
