### ISSUE TITLE
blog "Edit on Github" url is broke.

### ISSUE THREAD

**Issue by cpreston321** [nuxt/nuxt.com#1533]
If you go to any blog and click `Edit on Github` on aside it will bring you to a 404 on github.

Code that is incorrect: https://github.com/nuxt/nuxt.com/blob/a9b1e32c93714f23703f12add0f0c17cc518bd2a/pages/blog/%5Bslug%5D.vue#L66

Needs to be: 

```
https://github.com/nuxt/nuxt.com/edit/main/content/${article.value._file}
```

**Comment by uncenter** [comment]
I already have a PR open to fix this :)
#1532
