### ISSUE TITLE
Nuxt.com has not been opening

### ISSUE THREAD

**Issue by VectorChi** [nuxt/nuxt.com#1547]
I have tried across different browsers and asked a couple of people to try and it doesn't respond. For a couple of weeks now actually. I am not sure it's a widespread issue because there has not been any issue about it raised yet.

<img width="1721" alt="Screenshot 2024-04-05 at 11 35 53" src="https://github.com/nuxt/nuxt.com/assets/80969723/d005ab0a-a552-4a7c-87e4-bcba9d623957">

**Comment by Atinux** [comment]
Could you try using a proxy like https://1.1.1.1/?

**Comment by VectorChi** [comment]
Just did. It still isn't responding. 
<img width="593" alt="Screenshot 2024-04-05 at 12 24 44" src="https://github.com/nuxt/nuxt.com/assets/80969723/ecbe60d5-de39-46de-9af0-4482a9803c20">
