### ISSUE TITLE
[question] Is this a typo?

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nuxt/nuxt.com#1555]
https://nuxt.com/docs/guide/directory-structure/nuxt-config
![image](https://github.com/nuxt/nuxt.com/assets/10191085/7d5e76bb-307e-485c-8234-61d8819eac19)

**Comment by manniL** [comment]
Yes, should be *flat*

**Comment by DamianGlowala** [comment]
Resolved in https://github.com/nuxt/nuxt/pull/26752.
