### ISSUE TITLE
500 error: r.value is null

### ISSUE THREAD

**Issue by pmnzt** [nuxt/nuxt.com#1565]
Saw a weird error every time i tried to open: https://nuxt.com/docs/guide/directory-structure/pages#nested-routes
However opening the site and navigating to that page through the router is fine, it only happens when visiting the link.

OS: debian 12
Browser: FireFox stable 124.0.2 (64-bit)

screenshot: 
![image](https://github.com/nuxt/nuxt.com/assets/94640870/3ef2b0f1-675b-4450-a5bc-eb6ea04466aa)

**Comment by Atinux** [comment]
Nice catch! Thank you for reporting it @pmnzt
