### ISSUE TITLE
Nuxt offical website unable to show search dialog on Chrome

### ISSUE THREAD

**Issue by serkodev** [nuxt/nuxt.com#1572]
### Environment

macOS / Chrome

### Reproduction

1. Go https://nuxt.com/
2. Press <kbd>CMD</kbd> + <kbd>K</kbd> or the Search button on the navigation bar

### Describe the bug

The search input dialog does not show up

### Additional context

Only not works on Chrome (or Chromium) but works on Firefox / Safari

**Comment by danielroe** [comment]
This seems to work for me.

**Comment by serkodev** [comment]
It seems there are no issues now. When I encountered problems previously, I made sure to close all browser extensions and repeatedly tested the website in incognito mode, even in a all clean os and browser.
If no changes have been made to the code, it could possibly be related to CDN cache.
