### ISSUE TITLE
Doc is broken

### ISSUE THREAD

**Issue by v0id-4lpz** [nuxt/nuxt.com#1580]
Hey guys,
Doc looks broken.
![image](https://github.com/nuxt/nuxt/assets/51789915/a08c5167-8247-4db1-b966-155a4b9995d4)

Maybe your last commit @danielroe ?

**Comment by danielroe** [comment]
Seems fine to me 🤨

Maybe a cache issue?

**Comment by v0id-4lpz** [comment]
Cleared my cache and same issue on my smartphone 😕

**Comment by J3m5** [comment]
I'm having the same problem on mobile with Chrome and Firefox.

**Comment by danielroe** [comment]
We've been having an issue where the _HTML_ is cached by Vercel or Cloudflare, and referencing assets (in browser preload) from an old deployment...

**Comment by J3m5** [comment]
Isn't it the same problem as in https://github.com/nuxt/nuxt.com/issues/1569 ?

**Comment by lihbr** [comment]
Console error on Chrome latest: 
![image](https://github.com/nuxt/nuxt.com/assets/25330882/283f9806-4500-4137-8b11-96dc84ddd308)

**Comment by manniL** [comment]
Closing here in favor of https://github.com/nuxt/nuxt.com/issues/1569

But **please** send an HAR file for us to investigate if that happens to you!

**Comment by noook** [comment]
Github doesn't accept HAR files, so here it is uploaded to file.io

https://file.io/FMN3wpkD2WZU

**Comment by v0id-4lpz** [comment]
Going on Getting started then clicking on Server

![image](https://github.com/nuxt/nuxt.com/assets/51789915/ce08d1d6-c5f3-4705-9a00-bb597061b267)

HAR [nuxt.com_Archive 24-05-10 14-21-09.har.json](https://github.com/nuxt/nuxt.com/files/15274956/nuxt.com_Archive.24-05-10.14-21-09.har.json)

**Comment by v0id-4lpz** [comment]
Still down 24h later... Wtf lol

**Comment by manniL** [comment]
> Still down 24h later... Wtf lol

Not fully down, not the whole time. See https://github.com/nuxt/nuxt.com/issues/1580#issuecomment-2103326397

**Comment by v0id-4lpz** [comment]
Looks OK now
