### ISSUE TITLE
Missing styles for h5

### ISSUE THREAD

**Issue by Strift** [nuxt/nuxt.com#1596]
The docs do not have styles for h5 headers, you can see it in posts with a lot of sections and sub-sections, like the [v4 Migration guide](https://nuxt.com/docs/getting-started/upgrade#testing-nuxt-4).

I suggest at least making those titles bold so they stand out a bit more.

**Comment by benjamincanac** [comment]
We're using `@tailwindcss/typography` for the styling and it seems `h5` and `h6` are not styled on purposes, here is how they explain it on https://tailwindcss-typography.vercel.app:

![CleanShot 2024-06-12 at 10.15.09@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2024_06_12_at_10_15_09_2x_d3436a4f1f.png)
