### ISSUE TITLE
Dark mode does not work properly on Firefox Developer Edition

### ISSUE THREAD

**Issue by zzy-life** [nuxt/nuxt.com#1663]
### Environment

https://nuxt.com/

### Reproduction

Use Google and Firefox to open https://nuxt.com/, and you can find that the automatic recognition on Firefox is wrong, showing the dark mode
![image](https://github.com/user-attachments/assets/1774c787-68da-4b70-bfcc-0f03ecfc0842)
![image](https://github.com/user-attachments/assets/6171868e-f8d1-4797-9b71-a8eaa8f0254d)

### Describe the bug

firefox Developer Edition 131.0b5
And how to turn off dark mode?
I tried but it didn't work
colorMode: {
   preference: 'light'
},

**Comment by zzy-life** [comment]
> Maybe the default color mode of nuxt ui is dark. You can check the nuxt-color-mode field in localstorage, delete it, and then refresh to see.

After deleting it, it returns to normal. How can I specify light directly?

**Comment by zzy-life** [comment]
> Maybe the default color mode of nuxt ui is dark. You can check the nuxt-color-mode field in localstorage, delete it, and then refresh to see.

I tried it, but it didn't work.

![Image](https://github.com/user-attachments/assets/2f48bad1-8257-44db-886f-beeee0ad8d7e)
![Image](https://github.com/user-attachments/assets/430ec2d6-816d-472e-81ec-efa4b9036201)

**Comment by ikxin** [comment]
Or you can give it a try.

```js
colorMode: {
  preference: 'light',
  fallback: 'light',
}
```
